---
title: "Part 3"
author: "Claire Madden"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE}
# load packages


library(tidyverse)
library(ggplot2)
library(reshape2)

# read in data

median_salary <- read_csv("Median salary for doctoral recipients.csv")

```

```{r}
# exploration of data

# male employed
hist_male_emp <- ggplot(median_salary, aes(x = male_emp))+
  geom_histogram(bins = 10)

hist_male_emp

qq_male_emp <- ggplot(median_salary, aes(sample = male_emp))+
  geom_qq()

qq_male_emp

# female employed
hist_female_emp <- ggplot(median_salary, aes(x = female_emp))+
  geom_histogram(bins = 10)

hist_female_emp

qq_female_emp <- ggplot(median_salary, aes(sample = female_emp))+
  geom_qq()

qq_female_emp


# male post doc

hist_male_pd <- ggplot(median_salary, aes(x = male_pd))+
  geom_histogram(bins = 10)

hist_male_pd

qq_male_pd <- ggplot(median_salary, aes(sample = male_pd))+
  geom_qq()

qq_male_pd

# female post doc

hist_female_pd <- ggplot(median_salary, aes(x = female_pd))+
  geom_histogram(bins = 10)

hist_female_pd

qq_female_pd <- ggplot(median_salary, aes(sample = female_pd))+
  geom_qq()

qq_female_pd

# these are not looking to be very normally distributed, but because they are medians of a larget data set is it still okay to do t-test?
# or should i use Mann - Whitney U (wilcoxon rank sum) test for rank? - risk loss of resolution

```






```{r}
# Does median salary differ significantly between male and female starting postdoc positions?

test_pd <- wilcox.test(median_salary$male_pd, median_salary$female_pd, paired = TRUE)

test_pd

# test received a warning message "cannot compute exact pvalue with ties"

# non significant p value

```




```{r}
# Does median salary differ significantly between male and female PhD recipients in non-postdoc employment positions?

test_emp <- wilcox.test(median_salary$male_emp, median_salary$female_emp, paired = TRUE)

test_emp


# test received a warning message "cannot compute exact pvalue with ties"
# need to find out why test is defaulting to continuity correction

# significant p value = 0.00257 




```




```{r}

data_melt <- melt(median_salary[c('field', 'male_pd', 'female_pd', 'male_emp', 'female_emp')], id.vars = 1)

```


```{r}
# make side by side column graphs of median salary for each field in post doc

# maybe make a new dataframe first


pd_data <- data_melt %>% 
  filter(variable == "female_pd" | variable == "male_pd")


pd_graph <- ggplot(pd_data, aes(x = field, y = value))+
  geom_col(aes(fill = variable), position = "dodge")
  
  

pd_graph

```




```{r}
# make side by side column graphs of median salary for each field in employed


emp_data <- data_melt %>% 
  filter(variable == "female_emp" | variable == "male_emp")


emp_graph <- ggplot(emp_data, aes(x = field, y = value))+
  geom_col(aes(fill = variable), position = "dodge")

emp_graph

```




```{r}
# add box plot with each column

box_plot <- ggplot(data_melt, aes(x = variable, y = value, fill = variable))+
  geom_boxplot()

box_plot


```

