---
title: "Part 4"
author: "Claire Madden"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load packages

library(tidyverse)
library(stargazer)
library(car)

#Load edited dataset

faculty_salaries <- read_csv("faculty data edited.csv")
```

```{r}
#Some initial data exploration to get an early sense of any trends

#Salary by gender
sal_by_gender <- faculty_salaries %>% 
  group_by(Sex) %>% 
  summarize(
    mean = mean(Salary)
  )

#Salary by rank (professor, associate professor, assistant professor)
sal_by_rank <- faculty_salaries %>% 
  group_by(Rank) %>% 
  summarize(
    mean = mean(Salary)
  )

#Average years (since PhD, and of service) for each rank
sal_by_bothyears <- faculty_salaries %>% 
  group_by(Rank) %>% 
  summarize(
    mean_PhD = mean(Years_PhD),
    mean_service = mean(Years_Service)
  )

#Salary by years of service (number of years as faculty), color coded for gender, separated by discipline
sal_by_service <- ggplot(faculty_salaries, aes(x = Years_Service, y = Salary)) +
  geom_point(aes(color = Sex), alpha = 0.5) +
  facet_wrap(~ Discipline)

sal_by_service

#Salary by years since PhD, color coded for gender, separated by discipline
sal_by_years <- ggplot(faculty_salaries, aes(x = Years_PhD, y = Salary)) +
  geom_point(aes(color = Sex), alpha = 0.5) +
  facet_wrap(~ Discipline)

sal_by_years

#Salary by years of service (number of years as faculty), color coded for gender, separated by rank
sal_by_service_rank <- ggplot(faculty_salaries, aes(x = Years_Service, y = Salary)) +
  geom_point(aes(color = Sex), alpha = 0.5) +
  facet_wrap(~ Rank)

sal_by_service_rank

#Salary by years since PhD, color coded for gender, separated by rank
sal_by_years_rank <- ggplot(faculty_salaries, aes(x = Years_PhD, y = Salary)) +
  geom_point(aes(color = Sex), alpha = 0.5) +
  facet_wrap(~ Rank)

sal_by_years_rank

#Mean salary by discipline (A = theoretical, B = applied)
sal_discipline_mean <- faculty_salaries %>% 
  group_by(Discipline) %>% 
  summarize(
    mean = mean(Salary)
  )

```

```{r}
#Exploring possibilities of collinearity (focusing on years PhD, years of service)

col_df <- faculty_salaries %>% 
  select(Years_PhD, Years_Service, Salary)

pairs(col_df)

#Years_PhD and Years_Service appear to be highly correlated

```


```{r}
#Creating a saturated model for salary, including all variables:

#Rank - professor, associate professor, assistant professor
#Discipline - A = theoretical or B = applied
#Sex - male or female
#Years_PhD - years since getting PhD
#Years_Service - years as a faculty member

sal_lm1 <- lm(Salary ~ Rank + Discipline + Sex + Years_PhD + Years_Service, data = faculty_salaries)

summary(sal_lm1)

#Info from the model summary:
#For rank, the referene level is associate professor
#For sex, the reference level is female
#For discipline, the reference level is A (theoretical)
#Years_PhD and Years_Service are continuous 

#Coefficients for rank seem to make sense - compared to associate professor, a full professor makes a good deal more, and an assistant professor makes less (matches the means that were calculated above)

#Coefficient for sex seems to make sense - male faculty made more

#Coefficient for discipline seems to make sense - applied made more than theoretical

#Are years_PhD and years_service redundant? Do they sort of get at a similar thing? Which one is better? Are they both incorporated within rank?

#Based on overall p-value, the model does significantly predict salary (p < 0.001)

```

```{r}
#Another model, this time using years_service and not years_phd

sal_lm2 <- lm(Salary ~ Rank + Discipline + Sex + Years_Service, data = faculty_salaries)

summary(sal_lm2)

#Still weird that there is a negative coefficient for years of service - doesn't make sense!
```

```{r}
#What about a model with years since phd, instead of years of service?

sal_lm3 <- lm(Salary ~ Rank + Discipline + Sex + Years_PhD, data = faculty_salaries)

summary(sal_lm3)

#Positive coefficient for years since PhD, so better!
```

```{r}
#Now a model with only rank, discipline, and sex (not using years since PhD or years of service)

sal_lm4 <- lm(Salary ~ Rank + Discipline + Sex, data = faculty_salaries)

summary(sal_lm4)
```


```{r}
#Model diagnostics

#For lm1 (saturated model)

plot(sal_lm1)

#Homoscedasticity seems fine, residuals normality looks pretty good for majority of data (upper tail is a little strange)

plot(sal_lm2)

#Homoscedasticity seems fine, again residuals normality looks pretty good for majority of data (upper tail is a little strange)

plot(sal_lm3)

#Homoscedasticity seems fine, again residuals normality looks pretty good for majority of data (upper tail is a little strange)

plot(sal_lm4)

#Homoscedasticity seems fine, again residuals normality looks pretty good for majority of data (upper tail is a little strange)

#For the q-q, upper tail could be influenced that as rank/years get high, salaries start to increase non-linearly
```

```{r}
#VIF for each model

vif(sal_lm1)

#Years_PhD and Years_Service both have VIF values > 4 (7.5, 5.9) - remove one of them from the model? Remove both - is this incorporated into rank?

vif(sal_lm2)
vif(sal_lm3)
vif(sal_lm4)

#No other VIF values were higher than 4. Also, with the exception of Years_PhD in model 2, all were very close to one (and in that instance, the value was 2)

#AIC models comparison

lm1_aic <- AIC(sal_lm1) #9093.82
lm2_aic <- AIC(sal_lm2) #9096.81
lm3_aic <- AIC(sal_lm3) #9097.21
lm4_aic <- AIC(sal_lm4) #9095.45
```

```{r}
#What about trying two models with interaction terms - PhD * rank, and Service * rank

sal_lm5 <- lm(Salary ~ Rank + Sex + Discipline + Years_PhD + Rank*Years_PhD, data = faculty_salaries)

summary(sal_lm5)

#Doesn't increase model fit
```

